apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-app-167026275-java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-app-167026275-java-quarkus-sample
    app.kubernetes.io/part-of: test-app-167026275
  name: test-app-167026275-java-quarkus-sample
  namespace: nzcs02jc
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-app-167026275-java-quarkus-sample
    weight: 100
status: {}
